name: Build Gradle for Pull Request

on:
  pull_request:
    branches:
      - 1.21.1
      - 1.20.1
    types:
      - synchronize
      - opened
      - reopened

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build --scan